// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first, then .env
config({ path: ".env.local" });
config();

const postgresUrl = process.env["POSTGRES_URL"] || process.env["PRISMA_DATABASE_URL"];

if (!postgresUrl) {
  throw new Error("POSTGRES_URL or PRISMA_DATABASE_URL must be set in environment variables");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: postgresUrl,
  },
});
